### ISSUE TITLE
Bug if use where clause

### ISSUE THREAD

**Issue by diwms** [scoumbourdis/grocery-crud#211]
Hi all! I have little question. When in method's used where clause (for example):

``` php
$crud->where('manager', 1);
```

Search don't work. Ajax request return **500 Internal Server Error** and information that this column don't exist.

``` sql
Error Number: 1054 Unknown column 'manager' in 'having clause'

SELECT COUNT(*) AS `numrows`
FROM (`users`)
WHERE `manager` =  1
AND  `first_name`  LIKE '%query%'
OR  `last_name`  LIKE '%query%'
HAVING `manager` =  1

#Filename: /var/www/grocery_crud_model.php Line Number: 191
```

How to solve this bug? If remove where clause - search work fine. I hope you help me. And sorry for my bad english.

**Comment by v-volaju** [comment]
Good day. I am using the version 1.5.0 of GC and got the same problem. I am also unable to find the referenced code to be replaced.

**Comment by diwms** [comment]
@v-volaju Hi! This fix already on master branch. Could you please give more information about problem?

**Comment by v-volaju** [comment]
Hi. I am using CI 3.0 and GC 1.5.0 and this is the controller code from the accompanying GC sample. I just added a field called `deleted` which can have the value of 0 or 1. Now when I set the `where` condition, the search doesn't work properly.
```
public function customers_management()
	{
			$crud = new grocery_CRUD();
			$crud->set_table('customers');
		     $crud->where('deleted',0);
			$crud->columns('customerName','contactLastName','phone','city','country','salesRepEmployeeNumber','creditLimit');
			$crud->required_fields('customerName','contactLastName','phone');
			$crud->display_as('salesRepEmployeeNumber','from Employeer')
				 ->display_as('customerName','Name')
				 ->display_as('contactLastName','Last Name');
			$crud->set_subject('Customer');
			$crud->set_relation('salesRepEmployeeNumber','employees','lastName');
 
			$output = $crud->render();

			$this->_example_output($output);
	}
```
I hope you can check this out.

**Comment by darkbe** [comment]
i have this "search all" problem.
How to solve this bug?

**Comment by beodob** [comment]
You have relations?

**Comment by darkbe** [comment]
yes. relations with where, as in previous comment.
$crud->set_relation();
$crud->where();

**Comment by beodob** [comment]
In relation write
$crud->set_relation('field', 'table', 'table.field');

**Comment by darkbe** [comment]
thanks, but it is not good.
throws an error:

Error Number: 1054
Unknown column 'j93bfec8a.table.field' in 'field list'

**Comment by beodob** [comment]
Ps. $crud->where('custumers.deleted',0);

**Comment by v-volaju** [comment]
It's still not working with that. Meanwhile I switched to datatables theme but I still want to see how to fix this.

**Comment by beodob** [comment]
Screen send

**Comment by darkbe** [comment]
i add to employees_management() function in Examples.php:
$crud->where('employees.officeCode', '1');
Theme is flexigrid.

If i search "Patter" string with "Search all" option, then i get all the rows with officeCode=1. If i seach with "LastName", i just get a row.

It uses "or" instead of "and" here:
`officeCode` = '1' OR `lastName` LIKE '%patter%'

SELECT `employees`.*, jd29d42cf.city AS sd29d42cf FROM `employees` LEFT JOIN `offices` as `jd29d42cf` ON `jd29d42cf`.`officeCode` = `employees`.`officeCode` WHERE `employees`.`officeCode` = '1' OR `lastName` LIKE '%patter%' ESCAPE '!' OR `firstName` LIKE '%patter%' ESCAPE '!' OR `extension` LIKE '%patter%' ESCAPE '!' OR `email` LIKE '%patter%' ESCAPE '!' OR `jd29d42cf`.`city` LIKE '%patter%' ESCAPE '!' OR `file_url` LIKE '%patter%' ESCAPE '!' OR `jobTitle` LIKE '%patter%' ESCAPE '!' HAVING `employees`.`officeCode` = '1' LIMIT 10

**Comment by Pimnr47** [comment]
Hi,

I have been struggling with a similar problem. First I had a 500 error with Flexigrid with the AJAX_LIST call whenever I had a WHERE clause in my controller. The where clause was always related to a foreign key. This issue I fixed by replacing having with where on line 635.

Next I wanted to resolve the issue that it searches for your search string OR your where clause. I wanted to be AND. So I also changed the rest of the function after line 635 into this:

if (!empty($this->where))
                    foreach ($this->where as $where)
                        $this->basic_model->where($where[0], $where[1], $where[2]);

                $likes = array();
                
                foreach ($columns as $column) {
                    if (isset($temp_relation[$column->field_name])) {
                        if (is_array($temp_relation[$column->field_name])) {
                            foreach ($temp_relation[$column->field_name] as $search_field) {
                                $likes[$search_field] = $search_text;
                                //$this->or_like($search_field, $search_text);
                            }
                        } else {
                            $likes[$temp_relation[$column->field_name]] = $search_text;
                            //$this->or_like($temp_relation[$column->field_name], $search_text);
                        }
                    } elseif (isset($this->relation_n_n[$column->field_name])) {
                        //@todo have a where for the relation_n_n statement
                    } else {
                        $likes[$column->field_name] = $search_text;
                        //$this->or_like($column->field_name, $search_text);
                    }
                }
                
                $where_clause = "";
                foreach ($likes as $field => $search_text) {
                    $where_clause = $where_clause. " OR ".$field. " LIKE '%".$this->basic_model->escape_like_str($search_text)."%' ESCAPE '!'";
                }
                
                if(sizeof($likes)>0){
                    $where_clause = "(".substr($where_clause, 4).")";
                    $this->basic_model->where($where_clause);
                }

**Comment by zar0ku1** [comment]
I have this problem
Grosery CRUD 1.5.8

**Comment by scoumbourdis** [comment]
Re-opening issue as per above comments to investigate more to the problem

**Comment by scoumbourdis** [comment]
Hello All,

I can't reproduce this error. This is probably solved at the latest version. Can you please check the **latest master** version (https://github.com/scoumbourdis/grocery-crud/archive/master.zip) 

If the bug still occurs, please add as comments:
1. The code of your function
2. The error that you are getting

Thanks
Johnny

**Comment by zar0ku1** [comment]
if i use **WHERE** construction in **Controller** search dont work

```
if ($this->ion_auth->in_group('Operator'))
{
$crud->unset_edit();
$crud->unset_delete();
$crud->unset_export();
$crud->unset_print();

$crud->fields('LastName','LastNameLatin','FirstName','FirstNameLatin','Patronymic','PatronymicLatin','Date_of_born','Date_of_exam',
'Number', 'Blank', 'Nationality', 'File', 'Institutes');
$crud->field_type('Institutes', 'hidden');
$crud->callback_before_insert(array($this,'add_function'));
$crud->where('Institutes',$Institutes_id);
}
```

If I comment the line

`//$crud->where('Institutes',$Institutes_id);`

search works


Before that I completely updated on your link
problem still exists

**Comment by scoumbourdis** [comment]
Hello @zar0ku1 ,

Can you please also refer me to which search are you referring to? Are you referring to the all search or search by column?

Thanks
Johnny

**Comment by zar0ku1** [comment]
I'm talking about global search, not search by columns
No mistakes, nothing happens
The log file is clean

**Comment by zar0ku1** [comment]
Could you reproduce the problem?

**Comment by alvofr** [comment]
Hi - i can reproduce this issue with the latest master:
You use a table and a where clause:
`$crud->set_table('kontakte');`
`$crud->where('deleted',0);`

If i use "search all" in this case for "hausr" there is a 500er error coming up:

A Database Error Occurred
Error Number: 1054</p><p>Unknown column 'deleted' in 'having clause'
SELECT `kontakte`.`id`
FROM `kontakte`
WHERE `deleted` =0
OR  `name` LIKE '%hausr%' ESCAPE '!'
OR  `vorname` LIKE '%hausr%' ESCAPE '!'
OR  `email` LIKE '%hausr%' ESCAPE '!'
OR  `deleted` LIKE '%hausr%' ESCAPE '!'
HAVING `deleted` =0
Filename: E:/UwAmp/UwAmp/www/fm-wp/admin3/system/database/DB_driver.php</p><p>Line Number: 691

As you can see the `deleted` =0 has an issue in the HAVING clause, as the `deleted` is not part of the select.
Another issue will be the where clause with the ORs and the desired deleted=0.
This won't work as this needs to be an AND
WHERE `deleted` =0 AND (
`name` LIKE '%hausr%' ESCAPE '!'
OR  `vorname` LIKE '%hausr%' ESCAPE '!'
OR  `email` LIKE '%hausr%' ESCAPE '!'
OR  `deleted` LIKE '%hausr%' ESCAPE '!'
)
or you will use the HAVING for getting all rows with deleted=0 - in this case deleted must be selected as `kontakte`.`id`

So there is an issue with "search all" in case you use a "$crud->where"
I hope this helps fixing this bug.

best regards

**Comment by scoumbourdis** [comment]
Hello All,

I am glad to inform you that this bug is (finally) reproduced and also fixed. You can now have this functionality from the latest master version. I am doing some more testing in order to have a very cool release for version 1.6.0 just before Christmas.

Let me know if you have any issues with the fix.

Regards
Johnny

**Comment by scoumbourdis** [comment]
This is now released on version 1.6.0

**Comment by andipahlevy** [comment]
search not working when use $crud->where 

i am using GC version 1.6.0

**Comment by hunter205** [comment]
This bug still happen. I used v1.6.1. The newest one.

**Comment by Pimnr47** [comment]
@hunter205 Have you tried:

`$crud->where('confirmsheets .userName', $this->nativesession->get('user_session'));`
